### ISSUE TITLE
title slide for MA degree recipients and title slide for PhD degree recipients

### ISSUE THREAD

**Issue by ozanj** [ozanj/heoc20grads#9]
Current: "Master of Arts in Education"

should it be:
"Degree Recipients of the
Master of Arts in Education"

[and same for PhD]

I'm not sure. just find PDFs of some commencement programs from previous years and figure out which text is standard.

**Comment by cyouh95** [comment]
I couldn't really find too much info on this, but [this](https://youtu.be/HqxBdKqOFMk?t=1236) just lists the degree/program name (e.g., `Master of Arts in X` or `Doctor of X`) w/o any additional text. [This](https://youtu.be/7W8rqnmi3gE?t=1770) just has a general `Presenting our Graduates` before listing the names.

**Comment by ozanj** [comment]
OK! just leave those slides as they are
